local_costmap:
  plugins:
    - {name: static_map,       type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
    #- {name: obstacle_layer, type: "costmap_2d::VoxelLayer"} #Laser sensors
    #- {name: ultrasonic,   type: "range_sensor_layer::RangeSensorLayer"}

  update_frequency: 5.0
  publish_frequency: 50.0

  global_frame: "odom" #To inflate obstacles
  robot_base_frame: "base_link"

  #static_map: false
  rolling_window: true
  width: 6.0 #6
  height: 6.0 #6
  resolution: 0.05 #0.01
